import { AnimeTagsType } from "../../bus/filters/types";

export const AnimeTags: AnimeTagsType[] = [
  "-",
  "alternative present",
  "amnesia",
  "anti-hero",
  "asia",
  "based on a manga",
  "contemporary fantasy",
  "cops",
  "crime",
  "criminals",
  "demons",
  "detective",
  "detectives",
  "drama",
  "earth",
  "espionage",
  "gods",
  "japan",
  "male protagonist",
  "manga",
  "mind games",
  "mystery",
  "overpowered main characters",
  "philosophy",
  "plot continuity",
  "police",
  "present",
  "primarily adult cast",
  "primarily male cast",
  "psychological",
  "psychopaths",
  "revenge",
  "rivalries",
  "secret identity",
  "serial killers",
  "shinigami",
  "shounen",
  "supernatural",
  "thriller",
  "time skip",
  "tragedy",
  "urban",
  "urban fantasy",
  "vigilantes",
  "work",
];
