version: '3.5'

networks:
  net:
    driver: overlay
    attachable: true

services:
  frontend:
    image: docker.pkg.github.com/clowns-party/animeover-frontend/animeoverfrontend:production
    ports:
      - 3000:3000
