name: Build & Deploy Storybook
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build Storybook 🔧
        run: |
          npm install
          npm run build-storybook
        env:
          GH_TOKEN: ${{ secrets.DOCKER_GITHUB_ACCESS }}